language: android
dist: trusty

env:
  - REVIEWDOG_VERSION=0.9.11

android:
  components:
    - tools
    - platform-tools

sudo: false

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

cache:
  directories:
    - $HOME/.gradle

before_script:
  - chmod +x deploy_bintray.sh
  - chmod +x add_review.sh

script:
  - ./gradlew --daemon lintKotlin test

after_failure:
  - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o ./reviewdog
  - chmod +x ./reviewdog
  - ./add_review.sh

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy_bintray.sh
